# site settings
title: Devon & Simon are getting married!
subtitle:
email: devonandsimonwedding@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Duxbury Bay Maritime School
city: Duxbury
state: MA
zip_code: 02332
country: United States of America
phone: 781-934-7555

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
